// Central map of editor icons. Components import icons only from here, so
// swapping a glyph is a one-line change.
import {
  LuArrowDown,
  LuArrowUp,
  LuBadgeCheck,
  LuChevronDown,
  LuCopy,
  LuDownload,
  LuImage,
  LuInbox,
  LuLayoutTemplate,
  LuMessagesSquare,
  LuMoon,
  LuPalette,
  LuPen,
  LuPlus,
  LuSettings2,
  LuSmile,
  LuSun,
  LuTrash2,
  LuUpload,
  LuUsers,
  LuX,
} from 'react-icons/lu';

export {
  LuArrowDown,
  LuArrowUp,
  LuBadgeCheck,
  LuChevronDown,
  LuCopy,
  LuDownload,
  LuImage,
  LuInbox,
  LuLayoutTemplate,
  LuMessagesSquare,
  LuMoon,
  LuPalette,
  LuPen,
  LuPlus,
  LuSettings2,
  LuSmile,
  LuSun,
  LuTrash2,
  LuUpload,
  LuUsers,
  LuX,
};